#!/usr/bin/env bash
# Android dev env setup for 42 Lyon
# goinfre is machine-local and wiped periodically -> rerun this after a wipe
set -e

GOINFRE="/goinfre/$USER"
SDK="$GOINFRE/android/sdk"
STUDIO_DIR="$HOME/opt/android-studio"
TARBALL_GLOB="$GOINFRE/downloads/android-studio-*-linux.tar.gz"
CLT_URL="https://dl.google.com/android/repository/commandlinetools-linux-15859902_latest.zip"
ENV_FILE="$HOME/.42-android-env.zsh"
CLI="$SDK/cmdline-tools/latest/bin/android"
AVDMANAGER="$SDK/cmdline-tools/latest/bin/avdmanager"
# google_apis (not google_apis_playstore): userdebug build that ships sqlite3
AVD_IMAGE="system-images/android-36/google_apis/x86_64"
AVD_DEVICE="medium_phone"
AVDS=("phone_1" "phone_2")

PACKAGES=(
    "platform-tools"
    "platforms/android-37.0"
    "build-tools/36.0.0"
    "emulator"
    "$AVD_IMAGE"
)

echo "==> directories"
mkdir -p "$GOINFRE"/android/{sdk,avd} "$GOINFRE"/gradle "$GOINFRE"/downloads "$HOME/opt"

echo "==> android studio"
if [ -x "$STUDIO_DIR/bin/studio.sh" ]; then
    echo "    already installed"
else
    TARBALL=$(ls $TARBALL_GLOB 2>/dev/null | head -1)
    if [ -n "$TARBALL" ]; then
        echo "    extracting $(basename "$TARBALL") ..."
        tar -xzf "$TARBALL" -C "$HOME/opt"
    else
        echo "    !! no tarball in $GOINFRE/downloads/"
        echo "       get the Linux .tar.gz from https://developer.android.com/studio"
        exit 1
    fi
fi

echo "==> command line tools"
if [ -x "$CLI" ]; then
    echo "    already installed"
else
    echo "    downloading ..."
    mkdir -p "$SDK/cmdline-tools"
    curl -fL -o "$GOINFRE/downloads/cmdline-tools.zip" "$CLT_URL"
    unzip -q -o "$GOINFRE/downloads/cmdline-tools.zip" -d "$SDK/cmdline-tools"
    rm -rf "$SDK/cmdline-tools/latest"
    mv "$SDK/cmdline-tools/cmdline-tools" "$SDK/cmdline-tools/latest"
fi

export ANDROID_HOME="$SDK"
export ANDROID_SDK_ROOT="$SDK"

echo "==> sdk packages"
for pkg in "${PACKAGES[@]}"; do
    echo "    $pkg"
    "$CLI" --no-metrics sdk install "$pkg" > /dev/null
done

echo "==> avd directory"
# the android CLI writes AVDs to ~/.android/avd and ignores ANDROID_AVD_HOME,
# so point that path at goinfre instead
if [ -L "$HOME/.android/avd" ]; then
    echo "    link already in place"
else
    mkdir -p "$HOME/.android"
    rm -rf "$HOME/.android/avd"
    ln -s "$GOINFRE/android/avd" "$HOME/.android/avd"
    echo "    linked ~/.android/avd -> $GOINFRE/android/avd"
fi

echo "==> avd"
# android emulator create can't pick the image (it uses Play Store images),
# so use avdmanager instead; the image is installed with the sdk packages
for avd in "${AVDS[@]}"; do
    if "$AVDMANAGER" list avd -c 2>/dev/null | grep -qx "$avd"; then
        echo "    $avd already exists"
    else
        echo "    creating $avd ..."
        echo no | "$AVDMANAGER" create avd -n "$avd" -k "${AVD_IMAGE//\//;}" -d "$AVD_DEVICE" > /dev/null
    fi
done

echo "==> shell env"
cat > "$ENV_FILE" <<'ENV'
# Generated by setup-android.sh - do not edit, changes will be overwritten
export ANDROID_HOME=/goinfre/$USER/android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export ANDROID_AVD_HOME=/goinfre/$USER/android/avd
export GRADLE_USER_HOME=/goinfre/$USER/gradle
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:$HOME/opt/android-studio/bin
ENV
echo "    wrote $ENV_FILE"

if grep -q "42-android-env" "$HOME/.zshrc" 2>/dev/null; then
    echo "    already sourced from ~/.zshrc"
else
    echo "[ -f ~/.42-android-env.zsh ] && source ~/.42-android-env.zsh" >> "$HOME/.zshrc"
    echo "    added source line to ~/.zshrc"
fi

echo "==> kvm"
if [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
    echo "    ok - hardware acceleration available"
else
    echo "    !! no /dev/kvm access on this machine - emulator will be slow"
fi

echo "==> status"
echo "    sdk      $(du -sh $SDK 2>/dev/null | cut -f1)"
echo "    home     $(df -h ~ | tail -1 | awk '{print $4}') free"
echo "    goinfre  $(df -h /goinfre | tail -1 | awk '{print $4}') free"

echo ""
echo "==> done"
echo "    source ~/.zshrc"
for avd in "${AVDS[@]}"; do
    echo "    emulator -avd $avd &"
done
echo "    studio.sh"
